// Template generated by maketempl from file ../../include/ctmpl/list.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifndef LISTINT
#define LISTINT

#include "alloc.h"

#line 17 "../../include/ctmpl/list.tmpl"

#include <stdbool.h>

struct nodeint {
  struct nodeint *next;
  struct nodeint *prev;
  int data;
};

struct listint {
  int len;
  struct nodeint *first;
  struct nodeint *last;
};

// Basic access
typedef struct listint listint_t;
typedef struct nodeint *listint_iterator_t;
typedef void listint_proc(int data);

extern void listint_init(listint_t *l);
extern void listint_clear(listint_t *l);

extern void listint_append(listint_t *l, int data);
extern void listint_prepend(listint_t *l, int data);
extern void listint_appendlist(listint_t *l1, listint_t *l2);

extern int listint_remove(listint_t *l);
extern int listint_pop(listint_t *l);

extern int listint_front(listint_t *l);
extern int listint_last(listint_t *l);

extern bool listint_isempty(listint_t *l);
extern int listint_length(listint_t *l);

// in case == makes sense
extern void listint_uniquecopyappendlist(listint_t *l1, listint_t *l2);
extern void listint_uniqueappend(listint_t *l, int data);
extern bool listint_ismember(listint_t *l, int data);

// Iterating
extern void listint_foreach(listint_t *l, listint_proc *p);

extern void listint_begin(listint_iterator_t *i, listint_t *l);
extern listint_iterator_t listint_iterator(listint_t *l);
extern bool listint_done(listint_iterator_t *i); 
extern void listint_next(listint_iterator_t *i);
extern int listint_get(listint_iterator_t *i);
extern void listint_set(listint_iterator_t *i, int data);


#endif
