// WARNING: don't edit here!  
// This file has been automatically generated by 'rha_config.pl'.
// Instead edit 'rha_config.d'.

#include <stdarg.h>
#include "alloc.h"
#include "rha_init.h"

// (1) symbols
object_t symbol_sym;
object_t object_sym;
object_t fn_sym;
object_t bool_sym;
object_t int_sym;
object_t real_sym;
object_t mat_sym;


// (2) prototypes
object_t symbol_proto;
object_t object_proto;
object_t fn_proto;
object_t bool_proto;
object_t int_proto;
object_t real_proto;
object_t mat_proto;


// (3) type objects
object_t symbol_obj;
object_t object_obj;
object_t fn_obj;
object_t bool_obj;
object_t int_obj;
object_t real_obj;
object_t mat_obj;


// (4) functions


// (5) init
#define ADD_TYPE(ttt, TTT)   // ttt ## _t
  setptype(ttt ## _proto, TTT ## _T);
  ttt ## _obj = new();
  assign(root, ttt ## _sym, ttt ## _obj);
  assign(ttt ## _obj, proto_sym, ttt ## _proto);

void add_function(object_t module, symbol_t s, int rettype, void *code, int narg, ...)
{
  // create a new object
  object_t o = new_t(FN_T, fn_proto);

  // create a struct containing all info about the builtin function
  fn_t f = ALLOC_SIZE(size_of(fn_t));
  setraw(o, (void *) f);
  f->rettype = rettype;
  f->code = code;
  f->narg = narg;
  f->argtypes = ALLOC_SIZE(narg*size_of(int_t));

  // read out the argument types
  va_list ap;
  va_start(ap, narg);
  for (int i=0; i<narg; i++)
    f->argtypes[i] = va_arg(ap, int_t);
  va_end(ap);

  // finally add it to module
  assign(module, s, o);
}

#define ADD_MODULE(mmm)   // mmm ## .h
  module = new();
  assign(modules, mm ## _sym, module);

object_t rha_init()
{
  object_t root = new();

  // (5.1) create prototypes (TYPES)
  symbol_proto = new();
  object_proto = new();
  fn_proto = new();
  bool_proto = new();
  int_proto = new();
  real_proto = new();
  mat_proto = new();


  // (5.2) create symbols (SYMBOLS, TYPES, MODULES, functions)
  symbol_sym = symbol_new("symbol");
  object_sym = symbol_new("object");
  fn_sym = symbol_new("fn");
  bool_sym = symbol_new("bool");
  int_sym = symbol_new("int");
  real_sym = symbol_new("real");
  mat_sym = symbol_new("mat");


  // (5.3) create type objects (TYPES)
  ADD_TYPE(symbol, SYMBOL);
  ADD_TYPE(object, OBJECT);
  ADD_TYPE(fn, FN);
  ADD_TYPE(bool, BOOL);
  ADD_TYPE(int, INT);
  ADD_TYPE(real, REAL);
  ADD_TYPE(mat, MAT);


  // (5.4) add modules (MODULES, functions)
  object_t modules = new();
  assign(root, modules_sym, modules);
  object_t module = 0;


}
