// WARNING: don't edit here!  
// This file has been automatically generated by 'rha_config.pl'.
// Instead edit 'rha_config.d' (or 'rha_config.pl' if you must ;) )

#ifndef DATATYPES_H
#define DATATYPES_H

// (0) use the keyword to mark the datatypes and function in
// 'rha_config.d' that should be accessible in Rhabarber
#define _rha_

// (1) datatypes which are available in Rhabarber
#include "config.h"
#include <stdbool.h>
#ifdef HAVE_PYTHON
#undef _POSIX_C_SOURCE
#include <Python.h>
#endif
struct rha_object;
typedef int                       _rha_ symbol_t;
typedef struct rha_object *       _rha_ any_t;
#include "gtuple.h" 
#include "glist.h"  
typedef int                       _rha_ int_t; 
typedef bool                      _rha_ bool_t;
typedef struct gtuple*            _rha_ tuple_t;
typedef any_t (*_builtin_t)(tuple_t);
typedef _builtin_t                _rha_ builtin_t;
typedef double                    _rha_ real_t;
typedef struct _mat_t_ { 
  real_t *array;
  int_t  rows;
  int_t  cols;
  int_t  len;
}*                                _rha_ mat_t;
typedef char *                    _rha_ string_t;
typedef void *                    _rha_ address_t;
typedef struct glist *            _rha_ list_t;
typedef glist_iterator_t *        _rha_ list_it_t;
typedef PyObject *                _rha_ pyobject_t;


// (2) primtype id for all types
enum ptypes {
  VOID_T = 0,
  SYMBOL_T = 1,
  ANY_T = 2,
  INT_T = 3,
  BOOL_T = 4,
  TUPLE_T = 5,
  BUILTIN_T = 6,
  REAL_T = 7,
  MAT_T = 8,
  STRING_T = 9,
  ADDRESS_T = 10,
  LIST_T = 11,
  LIST_IT_T = 12,
  PYOBJECT_T = 13
};


// (3) prototypes for all types
extern any_t prototypes[14];
extern any_t fn_data_proto;
extern any_t implementation_proto;
extern any_t pattern_proto;


// (4) type objects
extern any_t void_obj;
extern any_t typeobjects[14];


// (5) ptype names
extern string_t ptype_names[];

// (6) symbols
extern symbol_t parent_sym;
extern symbol_t proto_sym;
extern symbol_t do_sym;
extern symbol_t quote_sym;
extern symbol_t type_sym;
extern symbol_t ptype_sym;
extern symbol_t this_sym;
extern symbol_t static_sym;
extern symbol_t root_sym;
extern symbol_t local_sym;
extern symbol_t void_sym;
extern symbol_t fn_data_sym;
extern symbol_t scope_sym;
extern symbol_t signature_sym;
extern symbol_t argnames_sym;
extern symbol_t fnbody_sym;
extern symbol_t priority_sym;
extern symbol_t hasproxy_sym;
extern symbol_t iter_sym;
extern symbol_t done_sym;
extern symbol_t get_sym;
extern symbol_t next_sym;
extern symbol_t msg_sym;
extern symbol_t ismacro_sym;
extern symbol_t check_sym;
extern symbol_t name_sym;
extern symbol_t args_sym;
extern symbol_t varargs_sym;
extern symbol_t no_frame_sym;
extern symbol_t patternliteral_sym;
extern symbol_t patterntype_sym;
extern symbol_t modules_sym;
extern symbol_t keywords_sym;
extern symbol_t prules_sym;
extern symbol_t curlied_sym;
extern symbol_t squared_sym;
extern symbol_t rounded_sym;
extern symbol_t tuple_forced_sym;
extern symbol_t method_call_sym;
extern symbol_t not_fn_sym;
extern symbol_t and_fn_sym;
extern symbol_t or_fn_sym;
extern symbol_t plus_fn_sym;
extern symbol_t minus_fn_sym;
extern symbol_t neg_fn_sym;
extern symbol_t times_fn_sym;
extern symbol_t divide_fn_sym;
extern symbol_t dottimes_fn_sym;
extern symbol_t dotdivide_fn_sym;
extern symbol_t equalequal_fn_sym;
extern symbol_t notequal_fn_sym;
extern symbol_t less_fn_sym;
extern symbol_t lessequal_fn_sym;
extern symbol_t greater_fn_sym;
extern symbol_t greaterequal_fn_sym;
extern symbol_t pattern_sym;
extern symbol_t apostrophe_fn_sym;
extern symbol_t domain_sym;
extern symbol_t object_sym;
extern symbol_t new_sym;
extern symbol_t addr_sym;
extern symbol_t clone_sym;
extern symbol_t ptypename_sym;
extern symbol_t print_fn_sym;
extern symbol_t vprint_fn_sym;
extern symbol_t to_string_sym;
extern symbol_t builtin_to_string_sym;
extern symbol_t address_to_string_sym;
extern symbol_t ls_sym;
extern symbol_t inc_sym;
extern symbol_t dec_sym;
extern symbol_t inc_copy_sym;
extern symbol_t dec_copy_sym;
extern symbol_t lookup_sym;
extern symbol_t lookup_local_sym;
extern symbol_t pcheck_sym;
extern symbol_t is_void_sym;
extern symbol_t location_sym;
extern symbol_t assign_sym;
extern symbol_t assign_many_sym;
extern symbol_t assign_fn_sym;
extern symbol_t extend_sym;
extern symbol_t has_sym;
extern symbol_t rm_sym;
extern symbol_t include_sym;
extern symbol_t subscribe_sym;
extern symbol_t eval_sym;
extern symbol_t callslot_sym;
extern symbol_t vcallslot_sym;
extern symbol_t pattern_lessthan_sym;
extern symbol_t signature_lessthan_sym;
extern symbol_t fn_data_entry_lessthan_sym;
extern symbol_t core_sym;
extern symbol_t proxy_fn_sym;
extern symbol_t create_function_sym;
extern symbol_t create_pattern_sym;
extern symbol_t create_fn_data_sym;
extern symbol_t create_fn_data_entry_sym;
extern symbol_t fn_fn_sym;
extern symbol_t macro_fn_sym;
extern symbol_t if_fn_sym;
extern symbol_t return_fn_sym;
extern symbol_t deliver_fn_sym;
extern symbol_t break_fn_sym;
extern symbol_t throw_fn_sym;
extern symbol_t while_fn_sym;
extern symbol_t for_fn_sym;
extern symbol_t try_fn_sym;
extern symbol_t colon_fn_sym;
extern symbol_t literal_sym;
extern symbol_t tic_fn_sym;
extern symbol_t toc_fn_sym;
extern symbol_t exit_fn_sym;
extern symbol_t run_fn_sym;
extern symbol_t map_fn_sym;
extern symbol_t prule_new_infix_sym;
extern symbol_t prule_new_prefix_sym;
extern symbol_t prule_new_postfix_sym;
extern symbol_t prule_new_freefix_sym;
extern symbol_t curlied_pr_sym;
extern symbol_t squared_pr_sym;
extern symbol_t apostrophe_pr_sym;
extern symbol_t plusplus_pr_sym;
extern symbol_t minusminus_pr_sym;
extern symbol_t not_pr_sym;
extern symbol_t divide_pr_sym;
extern symbol_t times_pr_sym;
extern symbol_t dotdivide_pr_sym;
extern symbol_t dottimes_pr_sym;
extern symbol_t prefix_minus_pr_sym;
extern symbol_t minus_pr_sym;
extern symbol_t plus_pr_sym;
extern symbol_t colon_pr_sym;
extern symbol_t in_pr_sym;
extern symbol_t less_pr_sym;
extern symbol_t lessequal_pr_sym;
extern symbol_t greater_pr_sym;
extern symbol_t greaterequal_pr_sym;
extern symbol_t equalequal_pr_sym;
extern symbol_t notequal_pr_sym;
extern symbol_t and_pr_sym;
extern symbol_t or_pr_sym;
extern symbol_t return_pr_sym;
extern symbol_t deliver_pr_sym;
extern symbol_t break_pr_sym;
extern symbol_t throw_pr_sym;
extern symbol_t if_pr_sym;
extern symbol_t try_pr_sym;
extern symbol_t while_pr_sym;
extern symbol_t for_pr_sym;
extern symbol_t fn_pr_sym;
extern symbol_t macro_pr_sym;
extern symbol_t equal_pr_sym;
extern symbol_t plusequal_pr_sym;
extern symbol_t minusequal_pr_sym;
extern symbol_t timesequal_pr_sym;
extern symbol_t divideequal_pr_sym;
extern symbol_t quote_pr_sym;
extern symbol_t parse_sym;
extern symbol_t resolve_sym;
extern symbol_t symbol_fn_sym;
extern symbol_t symbol_new_sym;
extern symbol_t symbol_equalequal_sym;
extern symbol_t symbol_name_sym;
extern symbol_t symbol_to_string_sym;
extern symbol_t symbol_valid_sym;
extern symbol_t tuple_fn_sym;
extern symbol_t tuple_new_sym;
extern symbol_t tuple_len_sym;
extern symbol_t tuple_get_sym;
extern symbol_t tuple_set_sym;
extern symbol_t tuple_to_list_sym;
extern symbol_t tuple_to_string_sym;
extern symbol_t tuple_make_sym;
extern symbol_t vtuple_make_sym;
extern symbol_t tuple_shift_sym;
extern symbol_t list_fn_sym;
extern symbol_t list_new_sym;
extern symbol_t list_copy_sym;
extern symbol_t list_len_sym;
extern symbol_t list_append_sym;
extern symbol_t list_prepend_sym;
extern symbol_t list_extend_sym;
extern symbol_t list_literal_sym;
extern symbol_t list_to_tuple_sym;
extern symbol_t list_to_string_sym;
extern symbol_t list_first_sym;
extern symbol_t list_last_sym;
extern symbol_t list_popfirst_sym;
extern symbol_t list_poplast_sym;
extern symbol_t list_begin_sym;
extern symbol_t list_done_sym;
extern symbol_t list_next_sym;
extern symbol_t list_get_sym;
extern symbol_t int_fn_sym;
extern symbol_t int_plus_sym;
extern symbol_t int_minus_sym;
extern symbol_t int_times_sym;
extern symbol_t int_divide_sym;
extern symbol_t int_neg_sym;
extern symbol_t int_equalequal_sym;
extern symbol_t int_notequal_sym;
extern symbol_t int_less_sym;
extern symbol_t int_lessequal_sym;
extern symbol_t int_greater_sym;
extern symbol_t int_greaterequal_sym;
extern symbol_t int_cmp_sym;
extern symbol_t int_cast_sym;
extern symbol_t int_to_string_sym;
extern symbol_t real_fn_sym;
extern symbol_t real_plus_sym;
extern symbol_t real_minus_sym;
extern symbol_t real_times_sym;
extern symbol_t real_divide_sym;
extern symbol_t real_neg_sym;
extern symbol_t real_equalequal_sym;
extern symbol_t real_notequal_sym;
extern symbol_t real_less_sym;
extern symbol_t real_lessequal_sym;
extern symbol_t real_greater_sym;
extern symbol_t real_greaterequal_sym;
extern symbol_t real_cmp_sym;
extern symbol_t real_cast_sym;
extern symbol_t real_exp_sym;
extern symbol_t real_sin_sym;
extern symbol_t real_cos_sym;
extern symbol_t real_to_string_sym;
extern symbol_t string_fn_sym;
extern symbol_t string_copy_sym;
extern symbol_t string_concat_sym;
extern symbol_t string_len_sym;
extern symbol_t string_equalequal_sym;
extern symbol_t string_get_sym;
extern symbol_t string_set_sym;
extern symbol_t string_to_string_sym;
extern symbol_t bool_fn_sym;
extern symbol_t bool_equalequal_sym;
extern symbol_t bool_to_string_sym;
extern symbol_t bool_not_sym;
extern symbol_t bool_or_sym;
extern symbol_t bool_and_sym;
extern symbol_t mat_fn_sym;
extern symbol_t mat_new_sym;
extern symbol_t mat_eye_sym;
extern symbol_t mat_rand_sym;
extern symbol_t mat_randn_sym;
extern symbol_t mat_cols_sym;
extern symbol_t mat_rows_sym;
extern symbol_t mat_len_sym;
extern symbol_t mat_copy_sym;
extern symbol_t mat_get_sym;
extern symbol_t mat_set_sym;
extern symbol_t mat_getl_sym;
extern symbol_t mat_setl_sym;
extern symbol_t mat_norm_sym;
extern symbol_t mat_max_sym;
extern symbol_t mat_min_sym;
extern symbol_t mat_scale_sym;
extern symbol_t mat_transpose_sym;
extern symbol_t mat_sort_sym;
extern symbol_t mat_solve_sym;
extern symbol_t mat_repmat_sym;
extern symbol_t mat_reshape_sym;
extern symbol_t mat_minus_sym;
extern symbol_t mat_plus_mat_sym;
extern symbol_t mat_minus_mat_sym;
extern symbol_t mat_times_mat_sym;
extern symbol_t mat_dottimes_mat_sym;
extern symbol_t mat_dotdivide_mat_sym;
extern symbol_t mat_plus_real_sym;
extern symbol_t mat_minus_real_sym;
extern symbol_t mat_times_real_sym;
extern symbol_t mat_divide_real_sym;
extern symbol_t real_plus_mat_sym;
extern symbol_t real_minus_mat_sym;
extern symbol_t real_times_mat_sym;
extern symbol_t mat_exp_sym;
extern symbol_t mat_sin_sym;
extern symbol_t mat_sinc_sym;
extern symbol_t mat_to_string_sym;
extern symbol_t messages_sym;
extern symbol_t warning_sym;
extern symbol_t error_sym;
extern symbol_t python_fn_sym;
extern symbol_t python_init_sym;
extern symbol_t python_newinteger_sym;
extern symbol_t python_newreal_sym;
extern symbol_t python_newstring_sym;
extern symbol_t python_newtuple_sym;
extern symbol_t python_newlist_sym;
extern symbol_t python_tuple_setitem_sym;
extern symbol_t python_tuple_getitem_sym;
extern symbol_t python_list_setitem_sym;
extern symbol_t python_list_getitem_sym;
extern symbol_t python_getint_sym;
extern symbol_t python_getreal_sym;
extern symbol_t python_getstring_sym;
extern symbol_t python_to_string_sym;
extern symbol_t python_importmodule_sym;
extern symbol_t python_runstring_sym;
extern symbol_t python_getversion_sym;
extern symbol_t python_lookup_sym;
extern symbol_t python_callable_sym;
extern symbol_t python_call_sym;
extern symbol_t symbol_sym;
extern symbol_t any_sym;
extern symbol_t int_sym;
extern symbol_t bool_sym;
extern symbol_t tuple_sym;
extern symbol_t builtin_sym;
extern symbol_t real_sym;
extern symbol_t mat_sym;
extern symbol_t string_sym;
extern symbol_t address_sym;
extern symbol_t list_sym;
extern symbol_t list_it_sym;
extern symbol_t pyobject_sym;


// (7) macros
#define UNWRAP_INT(o)     (unwrap_int(INT_T, o))
#define UNWRAP_BOOL(o)    (unwrap_int(BOOL_T, o))
#define UNWRAP_SYMBOL(o)  (unwrap_int(SYMBOL_T, o))
#define UNWRAP_REAL(o)    (unwrap_double(REAL_T, o))
#define UNWRAP_BUILTIN(o) (unwrap_builtin(BUILTIN_T, o))
#define UNWRAP_PTR(pt, o) (unwrap_ptr(pt, o))

#define WRAP_INT(i)       (wrap_int(INT_T, i))
#define WRAP_BOOL(b)      (wrap_int(BOOL_T, b))
#define WRAP_SYMBOL(s)    (wrap_int(SYMBOL_T, s))
#define WRAP_REAL(d)      (wrap_double(REAL_T, d))
#define WRAP_BUILTIN(p)   (wrap_builtin(BUILTIN_T, p))
#define WRAP_PTR(pt, p)   (wrap_ptr(pt, p))

#endif
