// WARNING: don't edit here!  
// This file has been automatically generated by 'rha_config.pl'.
// Instead edit 'rha_config.d'.

// (1) includes
#include "object.h"
#include "eval.h"
#include "bool_fn.h"


// (2) 'rha_init' creates the whole object hierarchy
extern object_t rha_init();
