// WARNING: don't edit here!  This file is automatically generated by
// 'rha_stub.pl'

#include "rha_stub.h"
#include "rha_stub_utils.h"

object_t rha_stub_init()
{
  object_t root = new();

  // add datatypes
  add_datatype(root, object_sym, OBJECT_T);
  add_datatype(root, int_sym, INT_T);

  // add functions
  add_function(root, new_sym, OBJECT_T, (void *) new, 0);
  add_function(root, clone_sym, OBJECT_T, (void *) clone, 1, OBJECT_T);
}
