// WARNING: don't edit here!  
// This file has been automatically generated by 'rha_config.pl'.
// Instead edit 'rha_config.d'.

#include <stdarg.h>
#include "alloc.h"
#include "rha_init.h"

// (1) symbols
symbol_t quote_sym;
symbol_t this_sym;
symbol_t root_sym;
symbol_t local_sym;
symbol_t modules_sym;
symbol_t symbol_sym;
symbol_t int_sym;
symbol_t eval_sym;

// (2) prototypes and objects
object_t int_obj;
object_t int_proto;
object_t real_obj;
object_t real_proto;

// (3) functions
//int_t int_plus(int_t, int_t);
object_t b_int_plus(tuple_t t) {
  return wrap(INT_T, int_proto, (void *) &int_plus(*RAW(int_t, tuple_get(t, 1)), *RAW(int_t, tuple_get(t, 2))));
}


//object_t eval(object_t env, object_t expr);
object_t b_eval(tuple_t t) {
  return eval(tuple_get(t, 1), tuple_get(t, 2));
}

//void_t tuple_set(tuple_t t, int_t i, object_t);
object_t b_tuple_set(tuple_t t) {
  tuple_set(*RAW(tuple_t, tuple_get(t, 1)), *RAW(tuple_t, tuple_get(t, 2)), tuple_get(t, 3));
}

// (4) init

#define ADD_TYPE(ttt, TTT)   // ttt ## _t\
  setptype(ttt ## _proto, TTT ## _T);\
  ttt ## _obj = new();\
  assign(root, ttt ## _sym, ttt ## _obj);\
  assign(ttt ## _obj, proto_sym, ttt ## _proto);

void add_function(object_t module, symbol_t s, int rettype, void *code, int narg, ...)
{
  // create a new object
  object_t o = new_t(FN_T, fn_proto);

  // create a struct containing all info about the builtin function
  fn_t f = ALLOC_SIZE(size_of(fn_t));
  setraw(o, (void *) f);
  f->rettype = rettype;
  f->code = code;
  f->narg = narg;
  f->argtypes = ALLOC_SIZE(narg*size_of(int_t));

  // read out the argument types
  va_list ap;
  va_start(ap, narg);
  for (int i=0; i<narg; i++)
    f->argtypes[i] = va_arg(ap, int_t);
  va_end(ap);

  // finally add it to module
  assign(module, s, o);
}

#define ADD_MODULE(mmm)   // mmm ## .h\
  module = new();\
  assign(modules, mm ## _sym, module);

object_t rha_init()
{
  object_t root = new();

  // (4.1) create prototypes (TYPES)
  symbol_proto = new();
  int_proto = new();

  // (4.2) create symbols (SYMBOLS, TYPES, MODULES, functions)
  proto_sym = symbol_new("proto");
  quote_sym = symbol_new("quote");
  int_sym = symbol_new("int");

  // (4.2) create type objects (TYPES)
  ADD_TYPE(int, INT);
  ADD_TYPE(symbol, SYMBOL);

  // (4.3) add modules (MODULES, functions)
  object_t modules = new();
  assign(root, modules_sym, modules);
  object_t module = 0;

  ADD_MODULE(object);
  add_function(module, new_sym, OBJECT_T, (void *) new, 0);
  add_function(module, clone_sym, OBJECT_T, (void *) clone, 1, OBJECT_T);

  ADD_MODULE(object);
  add_function(module, new_sym, OBJECT_T, (void *) new, 0);
  add_function(module, clone_sym, OBJECT_T, (void *) clone, 1, OBJECT_T);
}
