// WARNING: don't edit here!  This file is automatically generated by
// 'rha_config.pl'

#include "rha_init.h"

// (1) symbols
symbol_t quote_sym;
symbol_t this_sym;
symbol_t root_sym;
symbol_t local_sym;

// (2) prototypes
object_t int_proto;
object_t real_protot;

// (3) functions
//int_t int_plus(int_t, int_t);
object_t b_int_plus(tuple_t t) {
  object_t o = new_t(INT_T, int_proto);
  setraw(o, (void *) &int_plus(*RAW(int_t, tuple_get(t, 1)), *RAW(int_t, tuple_get(t, 2))));
  return o;
}


//object_t eval(object_t env, object_t expr);
object_t b_eval(tuple_t t) {
  return eval(tuple_get(t, 1), tuple_get(t, 2));
}

//void_t tuple_set(tuple_t t, int_t i, object_t);
object_t b_tuple_set(tuple_t t) {
  object_t o = new();
  setptype(o, VOID_T);
  tuple_set(*RAW(tuple_t, tuple_get(t, 1)), *RAW(tuple_t, tuple_get(t, 2)), tuple_get(t, 3));
  return o;
}

// (4) init

#define ADD_TYPE(ttt, TTT)   // ttt ## _t		\
  object_t ttt ## _obj = new();\
  ttt ## _proto = new();\
  setptype(ttt ## _proto, TTT ## _T);\
  assign(ttt ## _obj, proto_sym, ttt ## _proto);\
  assign(root, ttt ## _sym, ttt ## _obj);

#define ADD_FUNCTION()

object_t rha_init()
{
  object_t root = new();

  // (4.1) add datatypes and prototypes
  ADD_TYPE(int, INT);

  // (4.2) add functions
  object_t modules = new();
  assign(root, modules_sym, modules);
  
  // object.h
  add_function(modules, b_new_sym, OBJECT_T, (void *) new, 0);
  add_function(modules, b_clone_sym, OBJECT_T, (void *) clone, 1, OBJECT_T);
}
