// Template generated by maketempl from file hash.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#include "hashintint.h"


#line 41 "hash.tmpl"

#include <stdio.h>

typedef struct hashintint hash_t;
typedef struct hashnodeintint node_t;

/*
 * symtable
 */
void hashintint_init(hash_t *h)
{
  h->len = 0;
  h->numbins = 113;
  h->table = malloc(sizeof(node_t*) * h->numbins);
  for(int i = 0; i < h->numbins; i++)
    h->table[i] = 0;
}


void hashintint_clear(hashintint_t h)
{
  for(int i = 0; i < h->numbins; i++) {
    for(node_t *n = h->table[i]; n; n = n->next) {
      (void)(n->key);
      (void)(n->val);
    }
  }  
}


int hashintint_lookup(hash_t *h, int k)
{
  int hash = (k) % h->numbins;
  node_t *n = h->table[hash];

  while(n && !intcompare(n->key, k)) n = n->next;

  if(n) return n->val;
  else return 0;
}


void hashintint_assign(hash_t *h, int k, int v)
{
  int hash = (k) % h->numbins;
  
  node_t *n = h->table[hash];

  while(n && !intcompare(n->key, k)) n = n->next;

  if(n) n->val = v;
  else {
    h->len++;
    n = malloc(sizeof(node_t));
    n->next = h->table[hash];
    n->key = (k);
    n->val = (v);
    h->table[hash] = n;
  }
}


void hashintint_dump(hash_t *h, keyintintproc_t *kp, valueintintproc_t *vp )
{
  printf("len:  %d\n", h->len);
  printf("bins: %d\n", h->numbins);
  for(int i = 0; i < h->numbins; i++) {
    //printf("Bin %d\n", i);
    for(node_t *n = h->table[i]; n; n = n->next) {
      (*kp)(n->key); printf(" -> "); (*vp)(n->val); printf("\n");
    }
  }
}
