// Template generated by maketempl from file hash.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifndef HASHINTINT
#define HASHINTINT

#include <stdlib.h>
#include "intdefs.h"

#line 15 "hash.tmpl"

struct hashnodeintint
{
  struct hashnodeintint *next;
  int key;
  int val;
};

struct hashintint
{
  int len;
  int numbins;
  struct hashnodeintint **table;
};

typedef struct hashintint *hashintint_t;
typedef void valueintintproc_t(int);
typedef void keyintintproc_t(int);

extern void hashintint_init(hashintint_t h);
extern void hashintint_clear(hashintint_t h);
extern int hashintint_lookup(hashintint_t h, int k);
extern void hashintint_assign(hashintint_t h, int k, int v);
extern void hashintint_dump(hashintint_t h, keyintintproc_t (*kp), valueintintproc_t (*vp) );


#endif
