// Template generated by maketempl from file hash.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifndef HASHSTRINGINT
#define HASHSTRINGINT

#include "stringdefs.h"

#line 15 "hash.tmpl"

struct hashnodestringint
{
  struct hashnodestringint *next;
  string key;
  int val;
};

struct hashstringint
{
  int len;
  int numbins;
  struct hashnodestringint **table;
};

typedef struct hashstringint *hashstringint_t;
typedef void valuestringintproc_t(int);
typedef void keystringintproc_t(string);

extern void hashstringint_init(hashstringint_t h);
extern void hashstringint_clear(hashstringint_t h);
extern int hashstringint_lookup(hashstringint_t h, string k);
extern void hashstringint_assign(hashstringint_t h, string k, int v);
extern void hashstringint_dump(hashstringint_t h, keystringintproc_t (*kp), valuestringintproc_t (*vp) );


#endif
