// Template generated by maketempl from file hash.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#include "hashstringint.h"


#line 41 "hash.tmpl"

#include <stdio.h>

typedef struct hashstringint hash_t;
typedef struct hashnodestringint node_t;

/*
 * symtable
 */
void hashstringint_init(hash_t *h)
{
  h->len = 0;
  h->numbins = 113;
  h->table = malloc(sizeof(node_t*) * h->numbins);
  for(int i = 0; i < h->numbins; i++)
    h->table[i] = 0;
}


void hashstringint_clear(hashstringint_t h)
{
  for(int i = 0; i < h->numbins; i++) {
    for(node_t *n = h->table[i]; n; n = n->next) {
      free(n->key);
      (void)(n->val);
    }
  }  
}


int hashstringint_lookup(hash_t *h, string k)
{
  int hash = hashstring(k) % h->numbins;
  node_t *n = h->table[hash];

  while(n && !!strcmp(n->key, k)) n = n->next;

  if(n) return n->val;
  else return 0;
}


void hashstringint_assign(hash_t *h, string k, int v)
{
  int hash = hashstring(k) % h->numbins;
  
  node_t *n = h->table[hash];

  while(n && !!strcmp(n->key, k)) n = n->next;

  if(n) n->val = v;
  else {
    h->len++;
    n = malloc(sizeof(node_t));
    n->next = h->table[hash];
    n->key = strdup(k);
    n->val = (v);
    h->table[hash] = n;
  }
}


void hashstringint_dump(hash_t *h, keystringintproc_t *kp, valuestringintproc_t *vp )
{
  printf("len:  %d\n", h->len);
  printf("bins: %d\n", h->numbins);
  for(int i = 0; i < h->numbins; i++) {
    //printf("Bin %d\n", i);
    for(node_t *n = h->table[i]; n; n = n->next) {
      (*kp)(n->key); printf(" -> "); (*vp)(n->val); printf("\n");
    }
  }
}
