// Template generated by maketempl from file list.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifdef LIST
#define LIST

#line 1 "list.tmpl"

struct node_int {
  struct node_int *next;
  struct node_int *prev;
  int data;
};

struct list_int {
  struct node_int *first;
  struct node_int *last;
};

typedef struct list_int *list_int_t;


#endif
