// Template generated by maketempl from file list.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#include "list.h"

#line 16 "list.tmpl"


void list_int_init(list_int_t l)
{
  l->first = l->last = 0;
}

void list_int_append(list_int_t l, int data)
{
  struct node_int *n = malloc(sizeof(struct node_int));
  n->data = (data);
  
  if(l->last) {
    l->first = n;
    l->last = n;
  }
  else {
    l->last->next = n;
    n->prev = l->last;
    l->last = n;
  }
}
