// Template generated by maketempl from file tuple.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#include "tupleint.h"


#line 40 "tuple.tmpl"


void tupleint_init(tupleint_t *t, int len)
{
  t->len = len;
  t->array  = malloc(sizeof(int) * len);
  for(int i = 0; i < len; i++)
    t->array[i] = 0;
}


void tupleint_initto(tupleint_t *t, int len, int x)
{
  t->len = len;
  t->array  = malloc(sizeof(int) * len);
  for(int i = 0; i < len; i++)
    t->array[i] = x;
}


void tupleint_clear(tupleint_t *t)
{
  free(t->array);
}


int tupleint_length(tupleint_t *t)
{
  return t->len;
}


void tupleint_set(tupleint_t *t, int i, int x)
{
  t->array[i] = x;
}	


int tupleint_get(tupleint_t *t, int i)
{
  return t->array[i];
}	


void tupleint_fromlist(tupleint_t *t, listint_t *l)
{
  tupleint_init(t, listint_length(l));
  
  listint_iterator_t it;
  int i = 0;
  for(listint_begin(&it, l);
      !listint_done(&it);
      listint_next(&it), i++) {
    tupleint_set(t, i, listint_get(&it));
  }
}


void tupleint_foreach(tupleint_t *t, tupleint_proc *fct)
{
  for(int i = 0; i < t->len; i++)
    (*fct)(t->array[i]);
}
