// Template generated by maketempl from file tuple.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifndef TUPLEINT
#define TUPLEINT

#include <stdlib.h>

#line 17 "tuple.tmpl"

struct tupleint {
  int len;
  int *array;
};

typedef struct tupleint tupleint_t;
typedef void tupleint_proc(int v);

extern void tupleint_init(tupleint_t *t, int len);
extern void tupleint_initto(tupleint_t *t, int len, int x);
extern void tupleint_clear(tupleint_t *t);
extern int tupleint_length(tupleint_t *t);
extern void tupleint_set(tupleint_t *t, int i, int x);
extern int tupleint_get(tupleint_t *t, int i);
extern void tupleint_foreach(tupleint_t *t, tupleint_proc *fct);

// this is just stuff which maybe exists
#include "listint.h"

extern void tupleint_fromlist(tupleint_t *t, listint_t *list);


#endif
