// Template generated by maketempl from file vector.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#include "vectorint.h"


#line 14 "vector.tmpl"


void vectorint_init(struct vectorint *v, int len)
{
  v->len = len;
  v->array  = malloc(sizeof(int) * len);
}


void vectorint_set(struct vectorint *v, int i, int x)
{
  v->array[i] = x;
}	


int vectorint_get(struct vectorint *v, int i)
{
  return v->array[i];
}	
