// Template generated by maketempl from file vector.tmpl
//
// maketempl has been written by Mikio Braun, 2005
// mikio@first.fraunhofer.de
//

#ifndef VECTORINT
#define VECTORINT


#line 3 "vector.tmpl"

struct vectorint {
  int len;
  int array;
};

extern void vectorint_init(struct vectorint *v, int len);
extern void vectorint_set(struct vectorint *v, int i, int x);
extern int vectorint_get(struct vectorint *v, int i);


#endif
